[project]
name = "stundenplan24-wrapper"
version = "9.0.0"
description = "A wrapper for the Stundenplan24 APIs."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pytz~=2025.2",
    "curl_cffi",
    "pipifax-proxy-manager@git+https://github.com/Belissimo-T/pipifax-modules.git/#subdirectory=pipifax-proxy-manager"
]